---
baseURL: http://something-fresh.org/
languageCode: en-us
title: Karen Holley
module:
  imports:
    path: github.com/StefMa/hugo-fresh
googleAnalytics: 
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  openGraph: true
  description: 
  navbarlogo:
    image: logos/logo.png
    link: "/"
  font:
    name: Open Sans
    sizes:
    - 400
    - 600
  hero:
    title: Grow Yourself to Grow Your Vision
    subtitle: I help leaders feel less overwhelmed and more in control so that they can grow their vision for their lives and for their institutions
    buttontext: About me
    buttonlink: "#"
    image: karen/k13.jpg
    clientlogos:
    - logo: systek
      url: https://google.com
    - logo: tribe
      url: https://stefma.github.io/hugo-fresh/
    - logo: kromo
      url: https://github.com/StefMa/hugo-fresh
    - logo: infinite
      url: https://hugo-fresh.vercel.app/
    - logo: gutwork
      url: https://bulma.io/
  navbar:
  - title: About
    url: "/about"
  - title: Grow
    url: "/grow"
  - title: Success Stories
    url: "/success_stories"
  - title: Reflections
    url: "/blog"
  - title: Socials
    sublinks:
    - title: Facebook
      url: "/"
    - title: Twitter
      url: "/"
    - title: Insta
      url: "/"
  - title: Sign up
    url: "/"
    button: true
  sidebar:
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: "/"
      - text: Account
        url: "/"
      - text: Settings
        url: "/"
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: "/"
      - text: Compose
        url: "/"
    - title: Images
      icon: image
      links:
      - text: Library
        url: "/"
      - text: Upload
        url: "/"
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: "/"
      - text: App settings
        url: "/"
  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Get started
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: 
    subtitle:
    clients:
    - name: Marta Masse
      quote: I have never met any professional so capable of being present for their client, noticing changes in their demeanour, an eyebrow or glow in their eye.
      job: Business Development Manager and Sales Consultant
      img: "1"
    - name: Freerk ten Hoor
      quote: Karin is very professional and has the great ability to understand challenges that people face irrelevant of their occupation. It helped me get a better understanding of my road ahead which is very exciting! 
      job: Director Europe & Head of Sales at Centtrip
      img: "2"
    - name: Karinna Jones-Ianello
      quote: I needed a new direction in life and Karin helped me find it. Because Karin in thoughtful, whip-smart, and caring she is able to guide her clients with clarity and a sense of purpose.
      job: English Teacher at CAMAS SCHOOL DISTRICT
      img: "1"
  section5:
    title: Drop us a line or two
    subtitle: We'd love to hear from you
    buttonText: Send Message
  section6:
    title: Unlock your potential as a leader
    subtitle: 
    buttonText: Send Message
    msg1: Feel more calm and centered
    msg2: Gain more clarity, confidence and joy
    msg3: Develop your authentic leadership style
  footer:
    logo: logofooter.png
    socialmediatitle: Follow Us
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: Coaching Services
        links:
        - text: Grow Yourself
          link: "/grow"
        - text: Grow Your Team
          link: "/growÂ§"
        - text: Free Mastermind Classes
          link: "/"
      column2:
        title: "OTHER"
        links:
        - text: About
          link: /about
        - text: Success Stories
          link: /success_stories
        - text: Reflections
          link: /blog
